In [5]:
print(1)

1


In [11]:
import numpy
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [15]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [17]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
import cv2


In [30]:
im_g=cv2.imread("smallgray.png",0)
im_g

In [32]:
import cv2

In [42]:
im_g=cv2.imread('smallgray.png',0)
im_g

In [44]:
import os

In [47]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 '01.Dictionary',
 '02.Project',
 'Commands.md',
 'README.md',
 'supermarkets.zip',
 'Testing.ipynb']

In [52]:
cd 02.Project

[WinError 2] The system cannot find the file specified: '02.Project'
D:\Forest\GitHub_Master\10_Apps\02.Project


In [55]:
os.listdir()

['.ipynb_checkpoints',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Testing.ipynb',
 'Untitled.ipynb']

In [57]:
import cv2

In [59]:
im_g=cv2.imread('smallgray.png',0)

In [62]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [65]:
cv2.imwrite('newsmallgray.ong',im_g)

error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgcodecs\src\loadsave.cpp:732: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'


In [68]:
img_g=cv2.imread('smallgray.png',1)

In [72]:
print(img_g)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [73]:
cv2.imwrite('newsmallgray.png',img_g)

True